// GENERATED FILE - DO NOT MODIFY
// This file is auto-generated by bin/update_app_logo
// To add or remove logos, modify the script or update assets/logos/ directory

import 'package:anzio/gen/assets.gen.dart';

enum AppLogo {
  anzio_1_0(logoName: 'anzio_logo_1_0'),
  anzio_2_0(logoName: 'anzio_logo_2_0'),
  anzio_3_0(logoName: 'anzio_logo_3_0'),
  anzio_4_0(logoName: 'anzio_logo_4_0'),
  anzio_5_0(logoName: 'anzio_logo_5_0'),
  anzio_6_0(logoName: 'anzio_logo_6_0'),
  anzio_6_1(logoName: 'anzio_logo_6_1');

  final String logoName;

  String get xcodeLogoName => logoName;
  String get androidActivityAliasName => 'com.parallelogram.anzio.$logoName';

  bool get free => this == AppLogo.anzio_1_0 || this == AppLogo.anzio_2_0;

  const AppLogo({
    required this.logoName,
  });

  AssetGenImage get asset {
    switch (this) {
      case .anzio_1_0:
        return Assets.logos.anzioLogo10.assets.anzioLogo10;
      case .anzio_2_0:
        return Assets.logos.anzioLogo20.assets.anzioLogo20;
      case .anzio_3_0:
        return Assets.logos.anzioLogo30.assets.anzioLogo30;
      case .anzio_4_0:
        return Assets.logos.anzioLogo40.assets.anzioLogo40;
      case .anzio_5_0:
        return Assets.logos.anzioLogo50.assets.anzioLogo50;
      case .anzio_6_0:
        return Assets.logos.anzioLogo60.assets.anzioLogo60;
      case .anzio_6_1:
        return Assets.logos.anzioLogo61.assets.anzioLogo61;
    }
  }
}
